apiVersion: batch/v1
kind: Job
metadata:
  name: job
  annotations:
    deployment.plural.sh/sync-options: Force=True
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: job
          image: quay.io/prometheus/busybox:latest
          command: ["/bin/sh","-c","echo job succeds after 30s; sleep 30; exit 0"]
