apiVersion: batch/v1
kind: Job
metadata:
  name: pre-sync-check-a
  namespace: default
  labels:
    app: pre-sync-check-a
  annotations:
    plural.sh/sync-wave: "-3"
    deployment.plural.sh/sync-hook: "pre-sync"
    deployment.plural.sh/sync-hook-delete-policy: "succeeded"
spec:
  template:
    metadata:
      labels:
        app: pre-sync-check-a
    spec:
      restartPolicy: Never
      containers:
      - name: logger
        image: busybox:1.35
        command:
        - /bin/sh
        - -c
        - |
          echo "Job started at $(date)"
          echo "Running simple check job..."
          for i in $(seq 1 10); do
            echo "Log message $i - Current time: $(date)"
            sleep 1
          done
          echo "Job completed successfully at $(date)"
