apiVersion: deployments.plural.sh/v1alpha1
kind: ServiceDeployment
metadata:
  name: test-example
spec:
  namespace: test-example
  git:
    folder: service-test-example
    ref: main
  repositoryRef:
    kind: GitRepository
    name: plural-manifests
  clusterRef:
    kind: Cluster
    name: target-cluster
    namespace: default