apiVersion: batch/v1
kind: Job
metadata:
  name: post-upgrade-job
  annotations:
    helm.sh/hook: post-upgrade
    helm.sh/hook-weight: "1"
    helm.sh/hook-delete-policy: hook-succeeded
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: post-upgrade
          image: busybox
          command: ['sh', '-c', 'echo "Validating upgrade success..." && sleep 30']
