apiVersion: batch/v1
kind: Job
metadata:
  name: pre-multi-hook-job
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: pre-install
          image: busybox
          command: ['sh', '-c', 'echo "Running changed tasks..." && sleep 30']
