apiVersion: batch/v1
kind: Job
metadata:
  name: pre-install-job
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "0"
    helm.sh/hook-delete-policy: hook-succeeded
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: pre-install
          image: busybox
          command: ['sh', '-c', 'echo "Running test job..." && sleep 30']
