apiVersion: deployments.plural.sh/v1alpha1
kind: ServiceDeployment
metadata:
  name: failing-service
spec:
  git:
    folder: manifests/failing-service
    ref: master
  repositoryRef:
    kind: GitRepository
    name: plural-manifests
  clusterRef:
    kind: Cluster
    name: mgmt
    namespace: default