apiVersion: deployments.plural.sh/v1alpha1
kind: ServiceDeployment
metadata:
  name: test-failing
spec:
  git:
    folder: service-test-failing
    ref: main
  repositoryRef:
    kind: GitRepository
    name: plural-manifests
  clusterRef:
    kind: Cluster
    name: mgmt
    namespace: default