apiVersion: v1
kind: Pod
metadata:
  name: failing-after-10s
  namespace: default
spec:
  containers:
    - name: app
      image: busybox
      command: ["sh", "-c", "sleep 10 && exit 1"]
      ports:
        - containerPort: 80
