apiVersion: v1
kind: Pod
metadata:
  name: pod-with-invalid-pvc
spec:
  containers:
    - name: app
      image: busybox
      command: ["sleep", "3600"]
      volumeMounts:
        - name: test
          mountPath: /data
  volumes:
    - name: test
      persistentVolumeClaim:
        claimName: non-existing-pvc
